package javacore.Hheranca.test;

import javacore.Hheranca.domain.Funcionario;

// 0 - BLOCO DE INICIALIZAÇÃO ESTÁTICO DA SUPERCLASSE É EXECUTADO QUANDO A JVM CARREGAR A CLASSE PAI
// 1 - BLOCO DE INICIALIZAÇÃO ESTÁTICO DA SUBCLASSE É EXECUTADO QUANDO A JVM CARREGAR A CLASSE FILHA
// 2 - É ALOCADO ESPAÇO EM MEMORIA PARA O OBJETO DA SUPERCLASSE
// 3 - CADA UM DOS ATRIBUTOS DE SUPERCLASSE É CRIADO E INICIALIZADO COM OS VALORES DEFAULT OU O QUE FOR PASSADO
// 4 - O BLOCO DE INICIALIZACAO DA SUPERCLASSE É EXECUTADO NA ORDEM QUE APARECE
// 5 - O BLOCO CONSTRUTOR DA SUPERCLASSE É EXECUTADO
// 6 - É ALOCADO ESPAÇO EM MEMORIA PARA O OBJETO DA SUBCLASSE
// 7 - CADA UM DOS ATRIBUTOS DE SUBCLASSE É CRIADO E INICIALIZADO COM OS VALORES DEFAULT OU O QUE FOR PASSADO
// 8 - O BLOCO DE INICIALIZACAO DA SUBCLASSE É EXECUTADO NA ORDEM QUE APARECE
// 9 - O BLOCO CONSTRUTOR DA SUBCLASSE É EXECUTADO

public class HerancaTest02 {
    public static void main(String[] args) {
        Funcionario funcionario = new Funcionario("Lucas");
    }
}
